services:
  aria2:
    container_name: aria2
    build:
      dockerfile: qemu-git-openssl.Dockerfile
    environment:
      BT_TRACKER_URLS: https://cf.trackerslist.com/best_aria2.txt
      BT_TRACKER_CRON_ENABLE: false
    volumes:
      - "./download:/aria2/download"
      - "./.aria2:/aria2/.aria2"
    restart: unless-stopped
    ports:
      - "6800:6800"

  ariang:
    # 端口 6880
    image: p3terx/ariang
    container_name: ariang
    logging:
      options:
        max-size: 1m
    restart: unless-stopped
    depends_on:
      - aria2
    ports:
      - "6880:6880"
