services:
  aria2:
    container_name: aria2
    build:
      dockerfile: Dockerfile
    environment:
      BT_TRACKER_URLS: https://cf.trackerslist.com/best_aria2.txt
    volumes:
      - "./download:/aria2/download"
    networks:
      - aria2
    restart: unless-stopped

networks:
  aria2:
    attachable: true
    name: aria2
    external: false
