services:
  aria2:
    container_name: aria2
    image: localhost/aria2
    environment:
      CONF_PATH: false
    ports:
      - "6800:6800"
      - "6881-6999:6881-6999"
    command:
      - "aria2c"
      - "--conf-path=/aria2/config/aria2.conf"