#!/usr/bin/with-contenv sh

echo "$(date +'%Y-%m-%d %H-%M-%S')  更新 BT 服务器"

# 初始化结果变量
bt_trackers_list=""

# 遍历逗号分隔的 URL

for url in $(echo "${BT_TRACKER_URLS:-https://cf.trackerslist.com/best_aria2.txt}" | tr ',' ' ');
do
  # 请求 URL 并获取内容
  echo "$(date +'%Y-%m-%d %H-%M-%S')  请求 $url bt 列表"
  response=$(wget -qO- "$url" | sed '/^$/d' | tr '\n' ',' | sed 's/,$//')
  if [ -z "$response" ]; then
      echo "$(date +'%Y-%m-%d %H-%M-%S')  $url 获取 BT 列表失败"
  else
    # 拼接结果
    if [ -n "$bt_trackers_list" ]; then
      bt_trackers_list="$bt_trackers_list,$response"
    else
      bt_trackers_list="$response"
    fi
  fi
done

if [ -z "$bt_trackers_list" ]; then
    echo "$(date +'%Y-%m-%d %H-%M-%S')  获取 BT 全部列表失败"
    return 1
fi


# 拼接 id 字符串
id="$(uname -r)_$(date +%s)"

# 将字符串编码为 Base64
encoded_id=$(echo -n "$id" | base64)

json_data=$(cat <<EOF
{
  "id": "${encoded_id}",
  "jsonrpc": "2.0",
  "method": "aria2.changeGlobalOption",
  "params": [
    "token:${RPC_SECRET:-"12345678"}",
    {"bt-tracker":"$bt_trackers_list"}
  ]
}
EOF
)

repose=$(wget -qO- \
              --header "Content-Type: application/json" \
              --post-data "$json_data" \
              http://127.0.0.1:"${RPC_LISTEN_PORT:-"6800"}"/jsonrpc)

echo "$(date +'%Y-%m-%d %H-%M-%S')  更新 BT 服务器完成。${repose}"