#!/bin/sh

mkdir -p "${HOME}" && chmod 0700 "${HOME}"

mkdir -p "${HOME}/.aria2" && chmod 0700 "${HOME}/.aria2"

mkdir -p "${HOME}/config" && chmod 0700 "${HOME}/config"

touch "${HOME}/.aria2/aria2.session" && chmod 0700 "${HOME}/.aria2/aria2.session"

cp /etc/aria2/config/aria2.conf "${HOME}/config" && chmod 0700 "${HOME}/config/aria2.conf"

