name: test build

on:
  workflow_dispatch:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        run: |
          docker compose --progress plain build -build-arg aria2_name=aria2-1.37.0.tar.gz -build-arg aria2_version=release-1.37.0