name: test build

on:
  workflow_dispatch:

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        run: |
          docker compose --progress plain build